In [51]:
import torch
torch.__version__

'1.7.0'

## Introduction to Tensors
Tensor adalah objek matematika yang menyimpan data multidimensi dalam array, apa bedanya tensor dengan array? tensor dapat menyimpan data lebih dari 3 dimensis seperti gambar, audio ataupun video. namun dengan tipe data yang sama. sedangkan array hanya bisa menyimpan tiga dimensi dan dapat dengan tipe data yang berbeda beda. 

keduanya sama sama penting dalam deep learning karena dapat karena bida diolah secara matematis, seperti ditambah, dikali dan sebagainya

### Creating Tensor

#### Scalar
adalah suatu nilai tunggal atau angka tunggal yang hanya memiliki satu nilai saja dan 
tidak memiliki arah ataupun dimensi 

In [52]:
scalar = torch.tensor(10)
print(scalar)      # nilai skalar
print(scalar.ndim) # dimensi skalar
print(scalar.item()) # mengembalikan nilai sebagai integer

tensor(10)
0
10


#### Vector
adalah nilai berdimensi tunggal dan dapat berisi banyak angka

contohnya kamu dapat memiliki vektor [3, 2] untuk menjelaskan [bedrooms, bathrooms] pada rumahmu.  

In [53]:
vector = torch.tensor([2, 3])
print(vector)
print(vector.ndim)

tensor([2, 3])
1


vektor tersebut memiliki 1 dimensi. untuk menghitung dimensi yang dimiliki sebuah tensor, kamu dapat menghitung jumlah tanda kurung siku di bagian luar `([)` dan hanya perlu menghitung satu sisi saja

konsep penting lainnya adalah atribut `shape`. ini akan memberi tahu bagaimana elemen didalamnya disusun

In [54]:
"""kode ini mengahasilkan torch size bernilai 2. yang berarti vektor memiliki bentuk [2]
halini diakrenakan ada dua elemen yang ditempatkan didalam kurung siku siku"""
vector.shape

torch.Size([2])

#### Matrix
sama fleksibelnya dengan vektor, namun memiliki 2 dimensi

In [55]:
MATRIX = torch.tensor([[2, 3],
                       [4, 6]])
print(MATRIX) # nilai matrix
print(MATRIX.ndim) # dimensi matrix
print(MATRIX.shape) # ukuran matrix

tensor([[2, 3],
        [4, 6]])
2
torch.Size([2, 2])


#### Tensor
memiliki 3 dimensi atau lebih

In [56]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
print(TENSOR)
print(TENSOR.ndim)
print(TENSOR.shape)

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])
3
torch.Size([1, 3, 3])


bagaimana cara membaca shape dari tensor? apa maksud dari `[1, 3, 3]`?
![image.png](https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00-pytorch-different-tensor-dimensions.png)

Dimensi 0 adalah elemen tensor (keseluruhan tensor).

Dimensi 1 adalah baris (row).

Dimensi 2 adalah kolom (column) tiap barisnya.


In [57]:
TENSOR = torch.tensor([[[1, 2, 3,3],
                        [3, 6, 9,3],
                        [3, 6, 9,4],
                        [2, 4, 5,4]],
                        [[1, 2, 3,3],
                        [3, 6, 9,3],
                        [3, 6, 9,4],
                        [2, 4, 5,4]]])
print(TENSOR.shape)

torch.Size([2, 4, 4])


maka kesimpulannya adalah
| Nama | Deskripsi | Jumlah Dimensi | Biasanya Dilambangkan |
|-|-|-|-|  
|**Scalar**| Bilangan tunggal | 0 | Huruf kecil (`a`) |
|**Vector**| Bilangan dengan arah, bisa berisi banyak nilai | 1 | Huruf kecil (`y`) |
|**Matrix**| Susunan bilangan 2 dimensi (baris dan kolom) | 2 | Huruf kapital (`Q`) |
|**Tensor**| Susunan bilangan multidimensi | Bisa lebih dari 2 | Huruf kapital (`X`) |


## Random Tensors

Random tensor penting karena banyak Neural Network belajar dengan menggunakan nilai tensor secara random dan kemudian memperbaiki nilainya untuk merepresentasikan data

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers...`

In [58]:
# membuat tensor random dengan ukuran (3, 4)
random_tensor = torch.rand(size=(3, 4))
print(random_tensor) 
print(random_tensor.ndim) 

tensor([[0.6391, 0.5968, 0.3133, 0.4093],
        [0.7219, 0.6055, 0.6810, 0.1640],
        [0.8129, 0.9467, 0.8917, 0.6457]])
2


### zero and ones

terkadang kamu hanya perlu mengisi nilai tensor dengan nol atau satu

hal ini sering terjadi pada masking ( seperti menutupi beberapa nilai dengan nol agar model tidak mempelajarinya ) 

In [59]:
# membuat tensor yang berisi nol
zeros = torch.zeros(size=(3,4))
zeros, zeros.shape, zeros.ndim

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.Size([3, 4]),
 2)

In [60]:
# membuat tensor yang berisi satu
ones = torch.ones(size=(3,4))
ones, ones.shape, ones.ndim

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.Size([3, 4]),
 2)

### a range tensor and like

terkadang anda perlu nilai dengan range tertentu, seperti 1 sampai 10 ataupun 100

In [61]:
# Create a range of values 0 to 10
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Kadang-kadang Anda mungkin menginginkan satu tensor dengan tipe tertentu dengan bentuk yang sama dengan tensor lainnya.

Misalnya, tensor dengan semua angka nol dengan bentuk yang sama dengan tensor sebelumnya.

In [62]:
# Can also create a tensor of zeros similar to another tensor
ten_zeros = torch.zeros_like(input=zero_to_ten) # will have same shape
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes 

- Ada banyak tipe data tensor yang berbeda di PyTorch. Beberapa khusus untuk CPU, beberapa lebih baik untuk GPU.

- Jika ada `torch.cuda`, berarti tensor untuk GPU (karena GPU Nvidia menggunakan toolkit komputasi CUDA). 

- Tipe paling umum adalah `torch.float32` atau `torch.float` (32-bit floating point).

- Ada juga 16-bit (`torch.float16` atau `torch.half`) dan 64-bit (`torch.float64` atau `torch.double`). Dan juga ada integer 8-bit, 16-bit, 32-bit dan 64-bit.

- Precision adalah jumlah detail yang digunakan untuk menggambarkan angka. Semakin tinggi nilai precision (8, 16, 32), semakin banyak detail dan data yang digunakan untuk mengekspresikan angka.

- Tipe data precision rendah umumnya lebih cepat dihitung tapi mengorbankan akurasi. Precision tinggi lebih lambat tapi lebih akurat.

- Jadi pilih tipe data tensor yang sesuai kebutuhan antara kecepatan komputasi dan akurasi model.

In [63]:
# float 32 tensor
float_32_tensor = torch.tensor([1.0, 2.0, 3.0],
                                dtype=None, # tipe data tensor ( float32, float64 dll )
                                device=None, # tempat penyimpanan tensor, CPU/GPU ( DEFAULT CPU)
                                requires_grad=False # apakah tensor membutuhkan gradient untuk backprop. Diset True jika tensor merupakan parameter yang akan ditraining.
                                )
float_32_tensor.dtype

torch.float32

In [64]:
# float 64 tensor
float_64_tensor = torch.tensor([1.0, 2.0, 3.0],
                                dtype=torch.float64, # tipe data tensor ( float32, float64 dll )
                                device=None, # tempat penyimpanan tensor, CPU/GPU ( DEFAULT CPU)
                                requires_grad=False # apakah tensor membutuhkan gradient untuk backprop. Diset True jika tensor merupakan parameter yang akan ditraining.
                                )
float_64_tensor.dtype

torch.float64

**Note:** Tensor datatypes adalah salah satu dari tiga error yang akan sering dijumpai dengan Pytorch dan Deep Learning

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

Berikut penjelasan singkat terkait precision dengan tipe data tensor di PyTorch:

- Semakin tinggi nilai precision (8, 16, 32, 64), semakin besar jumlah bit yang digunakan untuk menyimpan setiap elemen tensor.

- Precision tinggi seperti float32 dan float64 menyimpan elemen tensor dengan akurasi tinggi. Namun memerlukan lebih banyak memori dan komputasi.

- Precision rendah seperti float16 dan int8 mengurangi kebutuhan memori dan komputasi. Tetapi akurasi elemen tensor menjadi lebih rendah.

- Umumnya float32 merupakan pilihan default terbaik untuk keseimbangan antara akurasi dan efisiensi komputasi.

- Float16 lebih cocok jika memori terbatas seperti di mobile atau ingin komputasi lebih cepat meski akurasi sedikit berkurang.

- Float64 diperlukan jika membutuhkan akurasi numeric yang sangat tinggi.

### Getting information from Tensors

Setelah Anda membuat tensor (atau orang lain atau modul PyTorch telah membuatnya untuk Anda), Anda mungkin ingin mendapatkan beberapa informasi darinya.

In [65]:
# Create a tensor
some_tensor = torch.rand(3, 4)

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.9792, 0.6705, 0.1011, 0.2674],
        [0.8453, 0.8752, 0.0768, 0.5185],
        [0.8495, 0.1919, 0.4156, 0.8437]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


**Note:** Ketika Anda mengalami masalah pada PyTorch, biasanya masalah tersebut berkaitan dengan salah satu dari tiga atribut di atas. 
- "what shape are my tensors? what datatype are they and where are they stored? what shape, what datatype, where where where"

### Manipulating Tensors
Dalam deep learning, data (gambar, teks, video, audio, struktur protein, dll) direpresentasikan sebagai tensor. Sebuah model belajar dengan menyelidiki tensor tersebut dan melakukan serangkaian operasi (bisa lebih dari 1.000.000) pada tensor untuk membuat representasi pola dalam data masukan.

- Addition
- Substraction 
- Multiplication (element-wise)
- Division
- Matrix multiplication

In [66]:
# Create a tensor of values and add a number to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [67]:
tensor * 10

tensor([10, 20, 30])

In [68]:
tensor - 10

tensor([-9, -8, -7])

In [69]:
tensor / 10

tensor([0.1000, 0.2000, 0.3000])

In [70]:
# built in function pytorch
print(torch.add(tensor, 10))
print(torch.mul(tensor, 10))


tensor([11, 12, 13])
tensor([10, 20, 30])


#### Matrix multiplication
terdapat dua jenis perkalian yaitu. Element Wise Multiplication dan Matrix Multiplication

In [71]:
# Element Wise Multiplication
print(tensor, "*", tensor)
print("Equal: ",tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equal:  tensor([1, 4, 9])


In [72]:
# Matrix Multiplication (dot product)
torch.matmul(tensor, tensor)

tensor(14)

apa perbedaanya?
| Operation | Calculation | Code |
|-|-|-|  
| Element-wise multiplication | [1 * 1, 2 * 2, 3 * 3] = [1, 4, 9] | `tensor * tensor` |
| Matrix multiplication | [1 * 1 + 2 * 2 + 3 * 3] = [14] | `tensor.matmul(tensor)` |

#### Common error (shape error)
Karena sebagian besar deep learning adalah mengalikan dan melakukan operasi pada matriks dan matriks memiliki aturan yang ketat tentang bentuk dan ukuran yang dapat digabungkan, salah satu kesalahan paling umum yang akan Anda temui dalam deep learning adalah ketidaksesuaian bentuk.

In [73]:
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)
print("shape Matrix A :", tensor_A.shape)
print("shape Matrix B :", tensor_B.shape)
torch.matmul(tensor_A, tensor_B) # (this will error)

shape Matrix A : torch.Size([3, 2])
shape Matrix B : torch.Size([3, 2])


RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

kita dapat membeuat perkalian kedua matrix itu dengan membuat dimensi didalamnya sama. salah satu caranya adalah dengan menggunakan **Matrix Transpose** (menukar dimension)

kamu dapat menvisualkannya disini http://matrixmultiplication.xyz/

In [ ]:
# Multiplication with Transopose
print("Tensor A :", tensor_A)
print("Tensor B :", tensor_B)
print("Tensor A Transpose :", tensor_A)
print("Tensor B Transpose :", tensor_B)
print()
print("A Multiply B Transpose \n", torch.mm(tensor_A, tensor_B.T)) # mm is shortcut for multiplication
print("B Multiply A Transpose \n", torch.mm(tensor_A.T, tensor_B))

Tensor A : tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
Tensor B : tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])
Tensor A Transpose : tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
Tensor B Transpose : tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])

A Multiply B Transpose 
 tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])
B Multiply A Transpose 
 tensor([[ 76., 103.],
        [100., 136.]])


#### Finding the min, max, mean, sum, etc ( tensor agregation )

In [ ]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {x.mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 90


RuntimeError: Can only calculate the mean of floating types. Got Long instead.

In [ ]:
print(f"Mean: {x.type(torch.float32).mean()}") # change to float datatype
print(f"Sum: {x.sum()}")

Mean: 45.0
Sum: 450


In [ ]:
# kmu juga bisa melakukan hal yang sama menggunakan "torch" secara langsung
torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x)

(tensor(90), tensor(0), tensor(45.), tensor(450))

In [ ]:
# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Index where max value occurs: 2
Index where min value occurs: 0


#### Reshaping, stacking, squeezing and unsqueezing
- reshaping `torch.reshape(input, shape)`: reshape an input tensor to a defined shape
- view `Tensor.view(shape)`: return a view of the input tensor of certain shape but keep the same memory as the original tensor
- stacking `torch.stack(tensors, dim=0)`: combine multiple tensors on top of each other (vstack) or side by side (hstack)
- squeeze `torch.squeeze(input)`: removes all *1* dimensions from a tensor
- unsqueeze `torch.unsqueeze(input, dim)`: add *1* dimensions to a tensor
- permute `torch.permute(input, dims)`: return a view of the input with dimensions permutes (swapperd) in a certain way

deep learning models (neural networks) are all about manipulating tensors in some way. And because of the rules of matrix multiplication, if you've got shape mismatches, you'll run into errors. These methods help you make sure the right elements of your tensors are mixing with the right elements of other tensors.

In [75]:
# Create a tensor
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [76]:
# add an extra dimension
x_reshaped = x.reshape(1, 7)

RuntimeError: shape '[1, 7]' is invalid for input of size 9

error tersebut muncul karena anda berusaha untuk mengubah tensor yang berisi 9 element menjadi 7. hal ini tidak dapat dilakukan kecuali anda mengubahnya menjadi 9

In [82]:
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape # dimesinya bertambah menjadi 2 dimensi

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [83]:
x_reshaped = x.reshape(9, 1)
x_reshaped, x_reshaped.shape # dimesinya bertambah menjadi 2 dimensi

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [84]:
x.ndim, x_reshaped.ndim # bener kan?

(1, 2)

##### view
keeps same data as original but changes view.
See more: https://stackoverflow.com/a/54507446/7900723

In [86]:
z = x.view(1, 9)
z, z.shape # really only creates a new view of the same tensor.

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [87]:
# Changing z changes x. because they use the same memory 
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

##### stack

In [91]:
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked 

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

##### squeeze

In [98]:
z, z.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [99]:
# delete dimesion
z.squeeze(), z.squeeze().shape

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

##### unsqueeze

In [106]:
# add dimensions
z.unsqueeze(dim=2), z.unsqueeze(dim=2).shape

(tensor([[[5.],
          [2.],
          [3.],
          [4.],
          [5.],
          [6.],
          [7.],
          [8.],
          [9.]]]),
 torch.Size([1, 9, 1]))

##### permute

In [112]:
# misal ketika ingin mengubahindex dari rgb gambar
x_orginial = torch.rand(size=(224,224, 3))
print("original shape", x_orginial.shape)

x_permuted = x_orginial.permute(2, 0, 1) # shift 2->0, 0->1, 1->2
print("permute shape", x_permuted.shape)

original shape torch.Size([224, 224, 3])
permute shape torch.Size([3, 224, 224])
