In [1]:
import torch
torch.__version__

'1.7.0'

## Introduction to Tensors
Tensor adalah objek matematika yang menyimpan data multidimensi dalam array, apa bedanya tensor dengan array? tensor dapat menyimpan data lebih dari 3 dimensis seperti gambar, audio ataupun video. namun dengan tipe data yang sama. sedangkan array hanya bisa menyimpan tiga dimensi dan dapat dengan tipe data yang berbeda beda. 

keduanya sama sama penting dalam deep learning karena dapat karena bida diolah secara matematis, seperti ditambah, dikali dan sebagainya

### Creating Tensor

#### Scalar
adalah suatu nilai tunggal atau angka tunggal yang hanya memiliki satu nilai saja dan 
tidak memiliki arah ataupun dimensi 

In [5]:
scalar = torch.tensor(10)
print(scalar)      # nilai skalar
print(scalar.ndim) # dimensi skalar
print(scalar.item()) # mengembalikan nilai sebagai integer

tensor(10)
0
10


#### Vector
adalah nilai berdimensi tunggal dan dapat berisi banyak angka

contohnya kamu dapat memiliki vektor [3, 2] untuk menjelaskan [bedrooms, bathrooms] pada rumahmu.  

In [7]:
vector = torch.tensor([2, 3])
print(vector)
print(vector.ndim)

tensor([2, 3])
1


vektor tersebut memiliki 1 dimensi. untuk menghitung dimensi yang dimiliki sebuah tensor, kamu dapat menghitung jumlah tanda kurung siku di bagian luar `([)` dan hanya perlu menghitung satu sisi saja

konsep penting lainnya adalah atribut `shape`. ini akan memberi tahu bagaimana elemen didalamnya disusun

In [8]:
"""kode ini mengahasilkan torch size bernilai 2. yang berarti vektor memiliki bentuk [2]
halini diakrenakan ada dua elemen yang ditempatkan didalam kurung siku siku"""
vector.shape

torch.Size([2])

#### Matrix
sama fleksibelnya dengan vektor, namun memiliki 2 dimensi

In [11]:
MATRIX = torch.tensor([[2, 3],
                       [4, 6]])
print(MATRIX) # nilai matrix
print(MATRIX.ndim) # dimensi matrix
print(MATRIX.shape) # ukuran matrix

tensor([[2, 3],
        [4, 6]])
2
torch.Size([2, 2])


#### Tensor
memiliki 3 dimensi atau lebih

In [13]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
print(TENSOR)
print(TENSOR.ndim)
print(TENSOR.shape)

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])
3
torch.Size([1, 3, 3])


bagaimana cara membaca shape dari tensor? apa maksud dari `[1, 3, 3]`?
![image.png](https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00-pytorch-different-tensor-dimensions.png)

Dimensi 0 adalah elemen tensor (keseluruhan tensor).

Dimensi 1 adalah baris (row).

Dimensi 2 adalah kolom (column) tiap barisnya.


In [18]:
TENSOR = torch.tensor([[[1, 2, 3,3],
                        [3, 6, 9,3],
                        [3, 6, 9,4],
                        [2, 4, 5,4]],
                        [[1, 2, 3,3],
                        [3, 6, 9,3],
                        [3, 6, 9,4],
                        [2, 4, 5,4]]])
print(TENSOR.shape)

torch.Size([2, 4, 4])


maka kesimpulannya adalah
| Nama | Deskripsi | Jumlah Dimensi | Biasanya Dilambangkan |
|-|-|-|-|  
|**Scalar**| Bilangan tunggal | 0 | Huruf kecil (`a`) |
|**Vector**| Bilangan dengan arah, bisa berisi banyak nilai | 1 | Huruf kecil (`y`) |
|**Matrix**| Susunan bilangan 2 dimensi (baris dan kolom) | 2 | Huruf kapital (`Q`) |
|**Tensor**| Susunan bilangan multidimensi | Bisa lebih dari 2 | Huruf kapital (`X`) |
